apiVersion: v1
kind: ConfigMap
metadata:
  name: dnsdist-conf
data:
  dnsdist.conf: |
    -- Include additional configurations
    includeDirectory("/etc/dnsdist/conf.d")
    
    infolog("Loading DNS server")

    -- Local Recursor
    newServer({address="127.0.0.1:1053", name="local-recursor"})

    -- Local authoritative server
    newServer({address="127.0.0.1:2053", pool="authoritative"})
    
    -- Set routes for Zone Transfer
    addAction(OrRule({QTypeRule(DNSQType.SOA), QTypeRule(DNSQType.AXFR), QTypeRule(DNSQType.IXFR)}), PoolAction("authoritative"))
    
    -- Set ACLs
    setACL('0.0.0.0/0')
    
    -- Listen for plain DNS queries
    setLocal("0.0.0.0:3053")
    
    -- Log queries to stdout
    local quiet = os.getenv("DNSDIST_QUIET")
    if quiet == nil or string.lower(quiet) ~= "yes" then
        addAction(AllRule(), LogAction('/dev/stdout', false, false, false))
    end
    
    -- Drop all queries for class CHAOS
    addAction(QClassRule(DNSClass.CHAOS), DropAction())
    
    -- Block hosts for 30 minutes that exceed 1000 queries in 1 seconds
    function maintenance()
        addDynBlocks(exceedQRate(1000, 1), "BANNED FOR QUERY OVERFLOW", 1800)
    end

    -- Cache responses
    -- local packet_cache = newPacketCache(10000)
    -- getPool(""):setCache(packet_cache)
    
    webserver("0.0.0.0:8083")
    setWebserverConfig({password=os.getenv("DNSDIST_WEBSERVER_PASSWORD"), apiKey=os.getenv("DNSDIST_API_KEY"), acl="0.0.0.0/0"})