apiVersion: v1
kind: Secret
metadata:
  name: secretvars
type: Opaque
data:
  ADMIN_PDNS_API_KEY: XXXXXXXXXXXX
  ADMIN_USER_PASSWORD: XXXXXXXXXXXX
  ADMIN_DB_USER: XXXXXXXXXXXX
  ADMIN_DB_PASS: XXXXXXXXXXXX
  AUTHORITATIVE_API_KEY: XXXXXXXXXXXX
  AUTHORITATIVE_WEBSERVER_PASSWORD: XXXXXXXXXXXX
  AUTHORITATIVE_DB_PASS: XXXXXXXXXXXX
  AUTHORITATIVE_DB_USER: XXXXXXXXXXXX
  RECURSOR_API_KEY: XXXXXXXXXXXX
  RECURSOR_WEBSERVER_PASSWORD: XXXXXXXXXXXX
  DNSDIST_API_KEY: XXXXXXXXXXXX
  DNSDIST_WEBSERVER_PASSWORD: XXXXXXXXXXXX
